#Database
DB_USERNAME: postgres
DB_PASSWORD: postgres
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: invoicer

#App config
APPLICATION_PORT: 8080
ACTIVE_PROFILE: test
UI_APP_URL: http://localhost:4200
JWT_SECRET: YUnhnded898b8HUY76g78