jwt:
  secret: ${JWT_SECRET}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      continue-on-error: false
      mode: always

flyway:
  locations: 'classpath:db/migration'

server:
  port: ${APPLICATION_PORT:8080}

ui:
  app:
    url: ${UI_APP_URL}